### ISSUE TITLE
Error: Error: Input required and not supplied: github_token

### ISSUE THREAD

**Issue by tigercosmos** [actions-ecosystem/action-remove-labels#272]
The following is the action config I use:

```
jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/done') }}
        with:
          labels: 'todo 🗒️'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/done') }}
        with:
          labels: 'status: resolved ✅'
```

And it turns out the result:
![image](https://user-images.githubusercontent.com/18013815/129806382-9c63805e-4c5a-49ce-9efc-400cbc5c808f.png)

where "remove" has error, but "add" works
