### ISSUE TITLE
Upgrade Node 12 to Node 16

### ISSUE THREAD

**Issue by Sugar-pack** [actions-ecosystem/action-remove-labels#413]
## What you want to add
Upgrade Node 12 to Node 16
## Why this is needed
Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases)
And all of the users receive a [warning](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) while running your action.

**Comment by Ana06** [comment]
I think this action is [forced to run in Node 16 now](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default) and it seems to still work. It would be good to update the action to Node 20 to get rids of all the warnings.

**Comment by kmasuhr** [comment]
If anyone is looking for alternative I suggest to use code below

```yaml
- uses: "actions/github-script@v7"
  name: "Add PR labels"
  with:
    script: |
      github.rest.issues.addLabels({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.payload.pull_request.number,
        name: 'LABEL_NAME'
      });
  if: github.event_name == 'pull_request'
```
