### ISSUE TITLE
HttpError: Resource not accessible by integration (???)

### ISSUE THREAD

**Issue by jessedoj** [actions-ecosystem/action-remove-labels#459]
## What happened

When using the following code:

`      - name: Remove tag on PR failure
        if: ${{ failure() }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            ready for testing`

We get the following on failure:

`Warning: failed to remove label: ready for testing: HttpError: Resource not accessible by integration
Error: Error: failed to remove labels: ready for testing`

## What you expected to happen
Some sort of success?

## Environment
We are using
`- uses: actions/checkout@v4`

Instead of V2 like is in the readme example.

**Comment by jdesulme** [comment]
You likely need to add a permissions block to your github actions workflow configuration file. 

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions. 

Some organizations by default set there permissions to read-only and you need to explictly define the permissions that need to be used. An example would be the following:

```
name: Auto Remove Label To PR 

on:
  pull_request:
    types: [closed]

permissions: 
  contents: read
  id-token: write
  pull-requests: write

jobs:
  do-things:
    timeout-minutes: 5
    name: Remove label to closed PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "ready for review"
```
